### ISSUE TITLE
请问你pages文件夹里的public公共页面该怎么用啊？

### ISSUE THREAD

**Issue by NinjaJin** [zhangyanzt/vue-apicloud#12]

**Comment by zhangyanzt** [comment]
`api.openWin({
	name: "winName",
    url: '../public/win.html',
    pageParam: {
        url: frameUrl,
        title: title,
        params:params //其他参数，整个pageParam会原样不动传到frame中
    }
});`


大体是这样，路径可能跟这个项目的不一样，自己看着处理就行
