### ISSUE TITLE
使用vux不成功

### ISSUE THREAD

**Issue by jlcool** [zhangyanzt/vue-apicloud#13]
使用vux不成功，请问怎么修改

**Comment by zhangyanzt** [comment]
vux需要用他们官方的vux-loader来处理组件路径，有需要的话可以自己配置。
也可以直接引用组件的真实路径
`import {XCircle} from "vux";`
修改为:
`import XCircle from "vux/src/components/x-circle";`
就可以直接使用了。

**Comment by jlcool** [comment]
什么也不修改，提示：
[HMR] Waiting for update signal from WDS... at 4.htm : 49
Uncaught Error: Cannot find module "!!vue-loader/node_modules/vue-style-loader!css-loader?sourceMap!../../../../_vue-loader@10.3.0@vue-loader/lib/style-rewriter?id=data-v-dbb1e888!less-loader!../../../../_vue-loader@10.3.0@vue-loader/lib/selector?t...<omitted>...e" at index.html : 3
Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools at 22.htm : 8011
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html at 22.htm : 8022
[WDS] Hot Module Replacement enabled. at 3.htm : 77
[WDS] Errors while compiling. Reload prevented. at 3.htm : 161
./~/_vux@2.9.1@vux/src/components/cell/index.vue
Module not found: Error: Can't resolve 'less-loader' in 'C:\Users\zhangjunyu\Documents\Project\vue-apicloud-master\node_modules\_vux@2.9.1@vux\src\components\cell'
 @ ./~/_vux@2.9.1@vux/src/components/cell/index.vue 3:0-253
 @ ./src/pages/html/index/app.js
 @ multi ./~/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://0.0.0.0:8010 webpack/hot/dev-server ./src/pages/html/index/app.js at 3.htm : 167
./~/_vux@2.9.1@vux/src/components/group/index.vue
Module not found: Error: Can't resolve 'less-loader' in 'C:\Users\zhangjunyu\Documents\Project\vue-apicloud-master\node_modules\_vux@2.9.1@vux\src\components\group'
 @ ./~/_vux@2.9.1@vux/src/components/group/index.vue 3:0-253
 @ ./src/pages/html/index/app.js
 @ multi ./~/_webpack-dev-server@2.11.2@webpack-dev-server/client?http://0.0.0.0:8010 webpack/hot/dev-server ./src/pages/html/index/app.js at 3.htm : 167

**Comment by jlcool** [comment]
安装了 less-loader 后提示 
Uncaught SyntaxError: Use of const in strict mode. at index.html : 5

**Comment by jlcool** [comment]
Use of const in strict mode 是系统版本太低了，现在基本没有问题了，谢谢

**Comment by jlcool** [comment]
使用 vuxLoader 后 
[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <App>

**Comment by jlcool** [comment]
配置loader的方式：
删除module.exports = config;
替换为：
module.exports = vuxLoader.merge(config, {
    options: {},
    plugins: [{
      name: 'vux-ui'
    }]
  })
重新运行 npm run dev
提示：Failed to mount component: template or render function not defined.

**Comment by jlcool** [comment]
参照 https://github.com/airyland/vux/issues/2569 解决Failed to mount component: template or render function not defined.问题
出现新问题：
_webpack_imported_module_1_vue_.default.user is not a function at

**Comment by jlcool** [comment]
是vuex-i18n 插件配置错误的原因，已经全部解决，感谢提供的帮助
