### ISSUE TITLE
npm run dev之后报错哦，如何解决哦，新手求解释。嘻嘻

### ISSUE THREAD

**Issue by blingbling-bin** [zhangyanzt/vue-apicloud#2]
npm run dev之后报错哦，如何解决哦，新手求解释。嘻嘻

> vue-multiple-pages@ dev /Users/blingbling_bin/Desktop/zhoubinbin/webapp/vue-apicloud-master
> cross-env NODE_ENV=development webpack-dev-server --inline --hot

/Users/blingbling_bin/Desktop/zhoubinbin/webapp/vue-apicloud-master/webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { const { join, resolve } = require('path');
                                                                    ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12

**Comment by zhangyanzt** [comment]
无法复现，请提供下node版本，建议升级到v6及以上版本

**Comment by oimmc** [comment]
我在api.js里面添加了这么个方法：
    /*自定义===================*/
    u.setBarFixedStyle = function(){
    	 var sysType = api.systemType;
        if(sysType == 'ios'){
        	$api.fixStatusBar($api.dom('header'));
        	api.setStatusBarStyle({
		    	style : 'light',
                color : '#374760'
		    });
        }else{
        	$api.fixStatusBar($api.dom('header'));
        	api.setStatusBarStyle({
		    	color:'#374760'
		    });
        }
	};
为什么调用的时候，说$api没有这个方法；甚至$api未定义？为何呢？

**Comment by zhangyanzt** [comment]
$api是 api.js 中的选择器，项目中默认没有引用 api.js,有需要的话可以自己引入
