### ISSUE TITLE
syncignore不起作用

### ISSUE THREAD

**Issue by wsqy** [zhangyanzt/vue-apicloud#5]
采用webpack构建的项目 .syncignore文件不起作用 同步时想忽略 node_modules文件夹一直失败 导致同步时编辑器卡死 请问改怎么办附 syncignore文件内容{**/*.js.map,**/node_modules/**,src/**,webpack.config.js,watch.js,package.json}

详细请看论坛帖子地址: http://community.apicloud.com/bbs/forum.php?mod=viewthread&tid=63966

**Comment by lanshengzhong** [comment]
@wsqy 测试发现使用老版本的编译器有用   新版本卡死  我用的1.5.5的  不过打代码用vscode  调试打包用官方1.5.5

**Comment by wsqy** [comment]
多谢您的回复
